
"""
Django settings for votesphere project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!k=yt0@0zgf@ocr_qc9ny(#6l-$2c4v^g1s^)%i@q^&9in-f0h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'elections',  # VoteSphere election management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'votesphere.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'votesphere.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (User uploads)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs (Legacy - now using OTP)
LOGIN_URL = 'request_otp'
LOGIN_REDIRECT_URL = 'voter_dashboard'
LOGOUT_REDIRECT_URL = 'home'

# ============= SECURE VOTING CONFIGURATION =============

# Voter identity hashing salt
# CRITICAL: Change this in production and keep it secret!
VOTER_SALT = 'votesphere-secret-salt-change-in-production-2026'

# RSA key paths for vote encryption/decryption
RSA_PUBLIC_KEY_PATH = BASE_DIR / 'keys' / 'public_key.pem'
RSA_PRIVATE_KEY_PATH = BASE_DIR.parent / 'secure_keys' / 'private_key.pem'

# Email configuration for OTP delivery using Postmark
import os

# Postmark API Configuration
POSTMARK_API_TOKEN = os.environ.get('POSTMARK_API_TOKEN', '1c7b67b8-f528-449a-8141-260b71d5ae03')

# Use Postmark SMTP for transactional emails (OTPs)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.postmarkapp.com'  # Transactional stream
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = POSTMARK_API_TOKEN  # Username is the API token
EMAIL_HOST_PASSWORD = POSTMARK_API_TOKEN  # Password is also the API token

# From email address (must be verified in Postmark)
DEFAULT_FROM_EMAIL = 'VoteSphere <atharva.ghuge24@sakec.ac.in>'

# Alternative: Use console backend for local testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# OTP Configuration
OTP_EXPIRATION_MINUTES = 5
COLLEGE_EMAIL_PATTERN = r'@.*\.(edu|ac\.in)$'  # Accepts .edu or .ac.in domains
# Examples: student@college.edu, student@sakec.ac.in
# To restrict to specific domain: r'@sakec\.ac\.in$'